import {
  ChangeDetectorRef,
  Component,
  ElementRef,
  OnDestroy,
  OnInit,
  ViewChild,
} from '@angular/core';
import { Subject, takeUntil } from 'rxjs';

import { ChatMessageItem } from '../chat.model';
import { ChatService } from '../chat.service';

@Component({
  selector: 'fullerstack-chat-list',
  templateUrl: './chat-list.component.html',
  styleUrls: ['./chat-list.component.scss'],
})
export class ChatListComponent implements OnInit, OnDestroy {
  private destroyed$ = new Subject<boolean>();
  chatSampleList: ChatMessageItem[] = [
    {
      author: 'GamerKademy',
      message: '#liltimmycraft',
      html: '#liltimmycraft',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLRA5ygU756xnaP55R4NcYJYgISIaAOz9AfzdNyO4Sv9y556FjYa8IRikjH9Avl0=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824818889,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'ItzKevGaming',
      message: 'KREEKCRAFT AND DOORMAN COLLAB',
      html: 'KREEKCRAFT AND DOORMAN COLLAB',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLQIVBRtYIbpVjRQkTqDcMZYwVdnPYIf1zJOn_ESug=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824819002,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Jeffy Yes',
      message: 'kreek you can get web shooters in custom arena',
      html: 'kreek you can get web shooters in custom arena',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLThAG0XZ6TANLbxPyUGAduxAo031cawbKwvAGdCLA=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824819163,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Christian Boi',
      message: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      html: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLRv7SHU9mCpy_c99ufhjTVGKgkKb7teWdEcdFUXR5pEWPbaWWhgloRh2jSdvoqD=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824819415,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Christian Boi',
      message: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      html: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLRv7SHU9mCpy_c99ufhjTVGKgkKb7teWdEcdFUXR5pEWPbaWWhgloRh2jSdvoqD=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824819666,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Luisa Caianiello',
      message:
        'If you do custom matches in Arena and get enough gold you can buy Spider-Man’s web shooters.',
      html: 'If you do custom matches in Arena and get enough gold you can buy Spider-Man’s web shooters.',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLQe0ZqHZsb-eQPy14KZzjRdqeB_Lwm5wHhqKQ=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824819793,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Jayden Peakman',
      message: 'what does ligma mean',
      html: 'what does ligma mean',
      avatarUrl:
        'https://yt4.ggpht.com/2yepBgDeq_07wcw-hxdfR3CGPvtifnZtFsI_mDgbvwYgpTGpGX2iLYZf1v3y-XU8QbZ2HFq8cP4=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824819991,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Odnanstar',
      message: 'could you do some more fnf videos?',
      html: 'could you do some more fnf videos?',
      avatarUrl:
        'https://yt4.ggpht.com/a0cS9S30remLGp1mxd-jKIn97EXRH4O0CZgUNTLgy6mk185NApem4lxWyJwkGw_DZw3IVGTGRlM=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824820334,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'The Sonic Fan',
      message: 'Play apex legends',
      html: 'Play apex legends',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLQFv2gHK-qi_Owbdrukvhm_1zZPhCR0jWJKIFNTGw=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824820655,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Sebastien Casimir',
      message: 'That song is copyrighted.',
      html: 'That song is copyrighted.',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLTNPRLhyI-eMT1gYE8uR10RmOAjM550qHNAyoxrfg=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824820765,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Ninja boi Kidbro',
      message: 'My step sister got ligma :(',
      html: 'My step sister got ligma :(',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLSFNLYTGtYk26kLQTB989gXc0ft9SqFnoNDOg=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824820909,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Can Camurlu',
      message: 'hi',
      html: 'hi',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLTZ-QQwD8NDMSVSloy_mqyDSiRtJrqlkS-fCiuH=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824821092,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Fishy Fish',
      message: 'kreek im going to see the new spiderman movie on the 15th lol',
      html: 'kreek im going to see the new spiderman movie on the 15th lol',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLQXXiy9C3qloUw6Tl1b-qm7JmaWsLMu2lcNE2sqfg=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824821371,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'antinerfer11 roblox',
      message:
        'KREEKCRAFT SHOULD ONLY BE ALLOWED TO PLAY MINECARFT AND ROBLOX THATS WHAT MY MOM SAID I therefore ground KreekCraft',
      html: '🛑KREEKCRAFT SHOULD ONLY BE ALLOWED TO PLAY MINECARFT AND ROBLOX THATS WHAT MY MOM SAID 😡😡😡 I therefore ground KreekCraft',
      avatarUrl:
        'https://yt4.ggpht.com/gRqoj2S8L5N-eW-W7kob_7c1zueMmaQ7TdXPioQ831yW83P4LTAXl-OEmBxgwddpNzHhmP4b3Q=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824821566,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Jacob Cowley',
      message: 'YOUR NOW EDICTED NOOOOO',
      html: 'YOUR NOW EDICTED NOOOOO',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLR0vs0UJ7_hR_JWTMyCBCWauQBYA7h05sCcc6r_jayurouUiLTlzjH_maFhN7jb=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824822070,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Dogewar Swag',
      message: 'Say Sugon',
      html: 'Say Sugon',
      avatarUrl:
        'https://yt4.ggpht.com/ezW9Xz_pv69OKXOIejkH793ZRqda6Cra7mQDSZDdHQyWMQ3KeQXO_kKqGr__QkrMb2XPL1gdm7s=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824822507,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'RealCatis',
      message: '@KreekCraft Who Can Buy Krekgma?',
      html: '@KreekCraft Who Can Buy Krekgma?',
      avatarUrl:
        'https://yt4.ggpht.com/DsbmlbXbCX9wNwp2ZnHTR9VTuVV4E_yVQuvurPtMSOThOHkJcnhSge4Dvz12IP1eNEkYAUeAlQ=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824822686,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'aydenashtonalex Gaming',
      message: 'did ur mom find out',
      html: 'did ur mom find out',
      avatarUrl:
        'https://yt4.ggpht.com/ANe0JeO3GjQkB2KvUZGFqrAgonbKeRMNZ3eP1jt-7JtN0EJmVrhyV2ys8m1k852XzO3cymZqFA=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824823036,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'ItzKevGaming',
      message: 'KREEKCRAFT AND DOORMAN COLLAB',
      html: 'KREEKCRAFT AND DOORMAN COLLAB',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLQIVBRtYIbpVjRQkTqDcMZYwVdnPYIf1zJOn_ESug=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824823388,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'farouk bendani',
      message: '10 kills',
      html: '10 kills',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLTKJsT1nxa_yLzUZgGafqfagODdWU87QVikfwQSTSRbsuV-Avloc-NQ_grKOjOg=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824823589,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Odnanstar',
      message: 'could you do some more fnf videos?',
      html: 'could you do some more fnf videos?',
      avatarUrl:
        'https://yt4.ggpht.com/a0cS9S30remLGp1mxd-jKIn97EXRH4O0CZgUNTLgy6mk185NApem4lxWyJwkGw_DZw3IVGTGRlM=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824823871,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Madison_x X',
      message: 'CHUG JUG WITH YOU',
      html: 'CHUG JUG WITH YOU',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLTN43L4jordS9IvDimEE-I1URVxfbje_Mp9oDN4uA=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824824206,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Blazecraft',
      message: 'Mhm',
      html: 'Mhm',
      avatarUrl:
        'https://yt4.ggpht.com/BwwmoDqHWrpJENNl8zG-tLZbZV1yfEVA6y-qob7UCvwPVGAdh192L202pk3_MksyJ3wKJkD4Dw=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824824381,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Natalis Vasquez',
      message: '?',
      html: '?',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLT5G5ocQNDcS1sm43h4AXE-8MtDBuUEeRXxzsGG=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824824691,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Dj Arbaz911',
      message: 'Did you quite jailbreak',
      html: 'Did you quite jailbreak',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLSWzf9MxrNhD7X_LiWdcMDdrsntg-Jgf7UxIqth=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824825121,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Christian Boi',
      message: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      html: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLRv7SHU9mCpy_c99ufhjTVGKgkKb7teWdEcdFUXR5pEWPbaWWhgloRh2jSdvoqD=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824825314,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Christian Boi',
      message: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      html: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLRv7SHU9mCpy_c99ufhjTVGKgkKb7teWdEcdFUXR5pEWPbaWWhgloRh2jSdvoqD=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824825719,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Marlene Acevedo rodriguez',
      message: 'gs',
      html: 'gs',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLS3cmIJjxnZ4ATvZmL2EZzpVqdOVL1QF4y8BxiH6Q=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824826017,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Tin Tan',
      message: 'mom credit card goes brrrrrrrr',
      html: 'mom credit card goes brrrrrrrr',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLSGZkDeeyP3ysNESyDHSS9zRdErnLaJrgS13hyq=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824826285,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'RealCatis',
      message: '@KreekCraft Who Can Buy Krekgma?',
      html: '@KreekCraft Who Can Buy Krekgma?',
      avatarUrl:
        'https://yt4.ggpht.com/DsbmlbXbCX9wNwp2ZnHTR9VTuVV4E_yVQuvurPtMSOThOHkJcnhSge4Dvz12IP1eNEkYAUeAlQ=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824826451,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'antinerfer11 roblox',
      message:
        'KREEKCRAFT SHOULD ONLY BE ALLOWED TO PLAY MINECARFT AND ROBLOX THATS WHAT MY MOM SAID I therefore ground KreekCraft',
      html: '🛑KREEKCRAFT SHOULD ONLY BE ALLOWED TO PLAY MINECARFT AND ROBLOX THATS WHAT MY MOM SAID 😡😡😡 I therefore ground KreekCraft',
      avatarUrl:
        'https://yt4.ggpht.com/gRqoj2S8L5N-eW-W7kob_7c1zueMmaQ7TdXPioQ831yW83P4LTAXl-OEmBxgwddpNzHhmP4b3Q=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824826924,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Jayden Peakman',
      message: 'what does ligma mean',
      html: 'what does ligma mean',
      avatarUrl:
        'https://yt4.ggpht.com/2yepBgDeq_07wcw-hxdfR3CGPvtifnZtFsI_mDgbvwYgpTGpGX2iLYZf1v3y-XU8QbZ2HFq8cP4=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824827118,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Odnanstar',
      message: 'could you do some more fnf videos?',
      html: 'could you do some more fnf videos?',
      avatarUrl:
        'https://yt4.ggpht.com/a0cS9S30remLGp1mxd-jKIn97EXRH4O0CZgUNTLgy6mk185NApem4lxWyJwkGw_DZw3IVGTGRlM=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824827352,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Fishy Fish',
      message: 'kreek im going to see the new spiderman movie on the 15th lol',
      html: 'kreek im going to see the new spiderman movie on the 15th lol',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLQXXiy9C3qloUw6Tl1b-qm7JmaWsLMu2lcNE2sqfg=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824827550,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Commander',
      message: 'yes',
      html: 'yes',
      avatarUrl:
        'https://yt4.ggpht.com/8cGYzu5G9h4Tp5eeGkavcyedaUm-NTQqEVQ-jaycd3mJDOwR3bwfxhoudzpxOp9KsajZuOGC=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824827890,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'The Sonic Fan',
      message: 'Play apex legends',
      html: 'Play apex legends',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLQFv2gHK-qi_Owbdrukvhm_1zZPhCR0jWJKIFNTGw=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824828290,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'saalig thegarbage',
      message: 'Kreek when did YOU start playing fortnite?',
      html: 'Kreek when did YOU start playing fortnite?',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLTCucZdpIMDFdupWUMRKOoeY5EwdNufVVJq0ITr4A=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824828599,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Kolo',
      message: 'for fps reasons',
      html: 'for fps reasons',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLS9JNaJo7i-Jzp-eVWMw3i8TxOc66qCz0qT2SZgPQ=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824829055,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Toofu King',
      message: 'No smoother',
      html: 'No smoother',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLSiidkO7f_H71i1y21mQTrJxcSgqNLd_cGXdi20=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824829567,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'bighead8910',
      message: 'LESS LAG',
      html: 'LESS LAG',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLTsx6cfkdi6ZpGm3DtBCB7IhSkt3hfnFj1Z3pLFpw=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824829829,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'ItzKevGaming',
      message: 'KREEKCRAFT AND DOORMAN COLLAB',
      html: 'KREEKCRAFT AND DOORMAN COLLAB',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLQIVBRtYIbpVjRQkTqDcMZYwVdnPYIf1zJOn_ESug=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824830264,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'MugmanTheBro',
      message: '',
      html: '😫',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLQbnc9E87UNvs-wIvNLkeBd_HAW4sJhKheGBOGB8Q=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824830632,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Dj Arbaz911',
      message: 'Yes',
      html: 'Yes',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLSWzf9MxrNhD7X_LiWdcMDdrsntg-Jgf7UxIqth=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824830776,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'LeafyXdDdd',
      message: 'sa',
      html: 'sa',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLT__pprxU_3Kv-k4pxW3KSvnmxpXq5RztexSdBE=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824831111,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Marlene Acevedo rodriguez',
      message: 'jose',
      html: 'jose',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLS3cmIJjxnZ4ATvZmL2EZzpVqdOVL1QF4y8BxiH6Q=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824831292,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'HZRD Tester',
      message: 'yes',
      html: 'yes',
      avatarUrl:
        'https://yt4.ggpht.com/IYGe3kSb8mn6p9m3EfpFVMWJ_eoI5T7dDmwHTvNvncOkHWObvIVlnQF_mXDkKUjgqA5rMBd-=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824831393,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'MättyMatus',
      message: 'yes',
      html: 'yes',
      avatarUrl:
        'https://yt4.ggpht.com/dR9D6AQt_qYwSOULBwzamD91BYvVTAayw4axF2M8GUn2dXx2lgubBxb7RGROL_82hwSuAaWE=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824831520,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Odnanstar',
      message: 'could you do some more fnf videos?',
      html: 'could you do some more fnf videos?',
      avatarUrl:
        'https://yt4.ggpht.com/a0cS9S30remLGp1mxd-jKIn97EXRH4O0CZgUNTLgy6mk185NApem4lxWyJwkGw_DZw3IVGTGRlM=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824831614,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'BellaCraft',
      message: 'Probably',
      html: 'Probably',
      avatarUrl:
        'https://yt4.ggpht.com/3dNhbayMaQRXSw2H-DHZ_v-PT7_CBYijbC_VqTVivK8Q03f83yfK9bLaEo1EA7fElDgU9Y4PvGk=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl:
        'https://yt3.ggpht.com/Y2vHmK20YnSdJnII62U_iLDECuwJFNJgmKSThnxTO3BsuH3T8dRZZOi9fG_u9CwOOU3cGE0fFg=s16-c-k',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824831761,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Focus',
      message: 'Yes',
      html: 'Yes',
      avatarUrl:
        'https://yt4.ggpht.com/tnHbhEd3res6WGleeVVgiZSrNpIdRZlD7hYgOut7-KFs_skLq6T5NgUehO2AV0nr70FaGPcr3A=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824831971,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'HARRISON HICKOX',
      message: '@KreekCraft How much do you like chapter 3?',
      html: '@KreekCraft How much do you like chapter 3?',
      avatarUrl:
        'https://yt4.ggpht.com/VtBqSCqyUqSmdghbeJ5DnzlrNLSDaeFA1GNBraSJoxCgjrVxFY1QaiOYjITAb0KgcNRZqwqx7g=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824832191,
      prefix: 'L7ckxulsNko',
    },
    {
      author: 'Christian Boi',
      message: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      html: '@KreekCraft If you lose 3 rounds you have to shave your hair.',
      avatarUrl:
        'https://yt4.ggpht.com/ytc/AKedOLRv7SHU9mCpy_c99ufhjTVGKgkKb7teWdEcdFUXR5pEWPbaWWhgloRh2jSdvoqD=s256-c-k-c0x00ffffff-no-rj',
      badgeUrl: '',
      donation: '',
      messageType: 'text-message',
      host: 'youtube',
      streamId: 'L7ckxulsNko',
      timestamp: 1638824832423,
      prefix: 'L7ckxulsNko',
    },
  ];

  constructor(readonly chRef: ChangeDetectorRef, readonly chatService: ChatService) {}

  ngOnInit(): void {
    console.log('ChatListComponent.ngOnInit()');
    this.updateChatList();
    // this.scrollToBottom();
  }

  updateChatList(): void {
    this.chatService.chatList$.pipe(takeUntil(this.destroyed$)).subscribe({
      next: (chatList) => {
        this.chRef.detectChanges();
      },
    });
  }

  itemClicked($event): void {
    console.log('ChatListComponent.itemClicked()', $event.target.addClass('chat-viewed'));
  }

  ngOnDestroy(): void {
    this.destroyed$.next(true);
    this.destroyed$.complete();
  }
}
