name: DEV

# Run on push only for dev/sandbox
# Otherwise it may trigger concurrently `push & pull_request` on PRs.
on:
  push:
    branches:
      - dev
      - sandbox
    paths-ignore:
      - '*.md'
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
      - 'tools/**'
      - 'graphs/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
      - 'tools/**'
      - 'graphs/**'
  workflow_dispatch:

jobs:
  #
  # Development Verification
  #
  development:
    timeout-minutes: 7
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get branch name
        id: branch
        run: echo ::set-output name=current_branch::${GITHUB_REF#refs/*/}

      - name: Install packages
        run: |
          yarn install --frozen-lockfile
          yarn prisma:generate

      - name: Run linter
        run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn lint:ci

      - name: Run builder
        run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn build:ci

      - name: Run tester
        run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn test:ci

      - name: Combine coverage
        run: |
          NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn coverage:merge

      - name: Push coverage to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage/lcov.combo.info'
