# Action Name
name: LintBuildTestE2E

# Controls when the action will run.
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - ci/*
      - releases/*
    paths-ignore:
      - '**.md'

  # Manual trigger OK
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      # - run: npm ci
      - run: echo ${{ github.head_ref }}
      - run: echo $(echo $GITHUB_REF | cut -d'/' -f 3)
      # - run: NX_BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3) npm run format:check
      # - run: NX_BRANCH=${GITHUB_REF##*/} npm run lint:ci
      # - run: NX_BRANCH=${GITHUB_REF##*/} npm run build:ci
      # - run: NX_BRANCH=${GITHUB_REF##*/} npm run test:ci
      # - run: NX_BRANCH=${GITHUB_REF##*/} npm run e2e:ci
