# Action Name
name: CI

# Controls when the action will run.
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - ci
    paths-ignore:
      - '**.md'

  # Manual trigger OK
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Grab the branch name
      - name: Get branch name
        id: branch
        run: echo ::set-output name=current_branch::${GITHUB_REF#refs/*/}

      # Grab dev api port
      - name: Get ci api port
        if: ${{ steps.branch.outputs.current_branch }} = dev
        id: port
        run: echo ::set-output name=api_port::4201

      # Grab ci api port
      - name: Get ci api port
        if: ${{ steps.branch.outputs.current_branch }} = ci
        id: port
        run: echo ::set-output name=api_port::4301

      # Grab main api port
      - name: Get main api port
        if: ${{ steps.branch.outputs.current_branch }} = main
        id: port
        run: echo ::set-output name=api_port::4401

      - name: We do
        run: echo Branch:${{ steps.branch.outputs.current_branch }}, Port${{ steps.port.outputs.api_port }}

      # Running node version
      # - name: Setup node 12
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 12.x

      # Install packages
      # - run: npm ci

      # - name: Run format check
      # - run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn format:check --base=${{ steps.vars.outputs.current_branch }} --head=HEAD

      # - name: Run linter
      # - run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn lint:ci

      # - name: Run build
      # - run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn build:ci

      # - name: Run unit tests
      # - run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn test:ci

      # - name: Push coverage
      # - run: find coverage -name lcov.info -exec echo -a {} \; | xargs lcov -o ./coverage/lcov.combo.info
      # - run: cat ./coverage/lcov.combo.info | ./node_modules/coveralls/bin/coveralls.js

      - name: Run e2e
        uses: cypress-io/github-action@v2
        with:
          # start: yarn api:ci &
          command: echo 'http://localhost:${{ steps.vars.outputs.api_port }}/api/ping'
          # wait-on: 'http://localhost:${{ steps.vars.outputs.api_port }}/api/ping'
          # wait-on-timeout: 120
          # command: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn e2e:ci
