# Action Name
name: LintBuildTestE2E

# Controls when the action will run.
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - ci/*
      - releases/*
    paths-ignore:
      - '**.md'

  # Manual trigger OK
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Grab the branch name
      - name: Get branch name
        id: vars
        run: echo ::set-output name=current_branch::${GITHUB_REF#refs/*/}

      # Running node version
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      # Install packages
      - run: npm ci

      - run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn format:check --base=${{ steps.vars.outputs.current_branch }} --head=HEAD
      - run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn lint:ci
      - run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn build:ci
      - run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn test:ci
      - run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn e2e:ci
